---
config:
  theme: 'neutral'
---
graph LR;
    C[/👨‍💼 💬 </br> '...!#?%...' </br> + ggf. Kontext/] --> VA(🤖 </br> Voranalyse </br>)
    VA --> I1(🤖 </br> Indikator 'Anschuldigung'</br>);
    VA --> I2(🤖 </br> Indikator 'Beleidigung'</br>);
    VA --> I3(🤖 </br> Indikator ...</br>);
    VA --> I4(🤖 </br> Indikator 'Gewaltaufruf'</br>);

    I1 --> AG(🤖 </br> Aggregation der</br> Ergebnisse</br>);
    I2 --> AG
    I3 --> AG
    I4 --> AG
    AG --> OUT[/Kategorisierung </br> ✅ ❌/]
